uint histogram_index(uint block_id, uint digit, uint num_blocks) {
    return digit * num_blocks + block_id;
}

uint key_index(uint block_id, uint offset, uint block_size) {
    return block_id * block_size + offset;
}

uint digit_value(uint key, uint digit_size, uint digit_id) {
    uint key = keys[key_index(gl_WorkGroupID.x, gl_InvocationID)];
    uint mask = ((1 << digit_size) - 1) << (digit_id * digit_size);
    return (key & mask) >> (digit_id * digit_size);
}
