#version 460

#include "common/structs.glsl"
#include "common/tiles.glsl"

#define NUM_THREADS 256

layout (local_size_x = NUM_THREADS) in;

layout (std430, binding = 0) readonly buffer ScreenSplats {
    ScreenSplat screen_splats[];
};

layout (std430, binding = 3) writeonly buffer InputKeys {
    uint count;
    uvec2 keys[];
} input_keys;

uniform uint uNumSplats;
uniform uvec2 uResolution;

shared uint sKeysToWrite;
shared uint sGlobalOffset;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint local_idx = gl_LocalInvocationIndex;

    if (local_idx == 0) {
        sKeysToWrite = 0;
    }
    barrier();

    uint keys_for_splat = 0;
    uvec2 tl_tile = uvec2(0);
    uvec2 br_tile = uvec2(0);
    uvec2 tile_res = tile_res(uResolution);

    if (idx < uNumSplats) {
        vec2 tl = screen_splats[idx].center + screen_splats[idx].offsets[1];
        vec2 br = screen_splats[idx].center + screen_splats[idx].offsets[2];
        tl_tile = tile_pos_from_ndc(tl, tile_res);
        br_tile = tile_pos_from_ndc(br, tile_res);
        keys_for_splat = num_tiles_in_quad_pos(tl_tile, br_tile, tile_res);
    }

    uint local_offset = atomicAdd(sKeysToWrite, keys_for_splat);  // Reserve space for keys for this splat within this WG's block
    barrier();

    if (local_idx == 0 && sKeysToWrite > 0) {
        sGlobalOffset = atomicAdd(input_keys.count, sKeysToWrite);  // Reserve this WG's space in key buffer
    }
    barrier();

    if (keys_for_splat > 0) {
        uint width = br_tile.x - tl_tile.x + 1;
        uint cnt = 0;
        for (uint y = br_tile.y; y <= tl_tile.y; ++y) {
            for (uint x = tl_tile.x; x <= br_tile.x; ++x) {
                uint tile_id = tile_id_from_pos(uvec2(x, y), tile_res.x);
                input_keys.keys[sGlobalOffset + local_offset + cnt] = uvec2(tile_id, screen_splats[idx].depth);
                cnt += 1;
            }
        }
    }
}