; Specifies which shader to use for each shader stage. Paths should be either absolute or relative to working directory.
[shaders]
comp = res/shaders/project_splat.comp
vert = res/shaders/splat.vert
frag = res/shaders/splat.frag

; Other file paths
[paths]
include = res/shaders
