; Specifies which shader to use for each shader stage. Paths should be either absolute or relative to working directory.
[shaders]
vert = res/shaders/direct.vert
;frag = res/shaders/pbr.fra
frag = res/shaders/screen_splat.frag

; Other file paths
[paths]
include = res/shaders/
