#version 460

#define NUM_THREADS 256
#define LOCAL_ARR_SIZE 256  // = NUM_THREADS
#define NUM_STRIDES 8  // = log_2(NUM_THREADS)

// Inclusive Hillis-Steele prefix scan - block sum scan
//   Algorithm retrieved from (and modified): https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-39-parallel-prefix-sum-scan-cuda#:~:text=A%20Naive%20Parallel%20Scan

layout (local_size_x = NUM_THREADS) in;

layout (std430, binding = 1) buffer BlockSum {
    uint block_sum[];
};

shared uint local_A[LOCAL_ARR_SIZE];
shared uint local_B[LOCAL_ARR_SIZE];

void main() {
    uint tid = gl_LocalInvocationID.x;

    local_A[tid] = block_sum[tid];
    barrier();

    // Inclusive scan
    for (uint stride = 1; stride < LOCAL_ARR_SIZE; stride <<= 1) {
        if (findLSB(stride) % 2 == 0) {
            local_B[tid] = local_A[tid] + (tid >= stride ? local_A[tid - stride] : 0);
        } else {
            local_A[tid] = local_B[tid] + (tid >= stride ? local_B[tid - stride] : 0);
        }
        barrier();
    }

    // Convert to exclusive, write back
    if (LOCAL_ARR_SIZE % 2 == 0) {
        block_sum[tid] = tid == 0 ? 0 : local_B[tid - 1];
    } else {
        block_sum[tid] = tid == 0 ? 0 : local_A[tid - 1];
    }
}